### ISSUE TITLE
HTML: lav cart siden hvor kunden kan se sin indeholdet af kurven

### ISSUE THREAD

**Issue by badranyoussef** [babanoelk/Cupcake#29]
På siden skal man kunne se en liste ovar de varer som kunden har lagt i kurven. Kunden skal kunne rette antal og slette varer fra kurven. Kunden skal også kunne vende retur til forsiden og tilføje flere cupcakes til kurven

**Comment by lassekh** [comment]
@badranyoussef Husk at man også skal kunne se det samlede ordrebeløb på kurv siden, som beskrevet i US-4:

US-4: Som kunde kan jeg se mine valgte ordrelinier i en indkøbskurv, så jeg kan se den samlede pris.

Bare så du tænker det ind ;)
